#include <iostream.h>
#include <conio.h>
void main()
{

clrscr();
cout<<"######## B C L Blade #############"<<endl;

cout<<"\n*********************************"<<endl;
int a;
int b;
int c;
int d;
float avg;

cout<<"enter 1st Digit = \xdb\t";
cin>> a;
cout<<"\nenter 2nd Digit = \xdb\t";
cin>> b;
cout<<"\nenter 3rd Digit = \xdb\t";
cin>> c;
cout<<"\nenter 4th Digit = \xdb\t";
cin>> d;

avg =(a+b+c+d)/4;

cout<<"\n\naverage of all four digits is = \xdb\t"<<avg;

cout<<"\n\n\xdb press any key to exit! \xdb ";

getch();

}
